#!/usr/bin/env bash

set -eux -o pipefail

cluster_name="kubernetes-webdev"

here=$(cd "$(dirname "$0")" && pwd)
kubeconfig_yaml=${here}/kubeconfig.yaml

"${here}/teardown"

k3d cluster create $cluster_name \
  --verbose \
  --config "${here}/k3d.yaml"
k3d kubeconfig get $cluster_name > "$kubeconfig_yaml"
