#!/usr/bin/env bash

set -eu -o pipefail

here=$(cd "$(dirname "$0")" && pwd)
k3d_yaml=${here}/k3d.yaml
cluster_name=$(yq -M .metadata.name "$k3d_yaml")
kubeconfig_yaml=${here}/kubeconfig.yaml

k3d cluster delete "$cluster_name" --verbose
rm -f "$kubeconfig_yaml"
